MapDisplay/urls.py
from django.contrib import admin
from django.urls import include, path
from screen import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('screen.urls', namespace='screen'))
]

screen/urls.py
from django.urls import path

from screen.views import menu_view, map_view, connect_view, info_view, connect_view

app_name = 'screen'

urlpatterns = [
    # path('', connect_view, name='connect_view'),
    # path('', connect_view, name='connect_view'),
    path('', connect_view, name='connect_view'),
    path('menu', menu_view, name='menu_view'),
    path('map', map_view, name='map_view'),
    path('info', info_view, name='info_view'),


]

screen/models.py
from django.db import models

# Create your models here.

screen/views.py
import time, json, os

from django.shortcuts import render, redirect
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from django.conf import settings

from .aux import scan, Mqtt, connect_wifi

BROKER = '192.168.1.100'
TOPIC = 'vikua/sinapsis/ta/device'

def get_coord(cliente_mqtt):
    """Retorna un objeto de tipo:
        {'lat':X, 'lng':Y, 'status': True} en caso de GPS DISPONIBLE
        o
        {'status': False} en caso de GPS NO DISPONIBLE
    """
    if cliente_mqtt.connected == False:
        cliente_mqtt = Mqtt(broker=BROKER, topic='#')

    cliente_mqtt.publish_message(topico=TOPIC, msg='coord')
    time.sleep(1)
    
    coordinates = cliente_mqtt.coord['coordinates']
    if coordinates != False:
        coordinates = coordinates.split(",")
        data = {'lat':float(coordinates[0]), 'lng':float(coordinates[1]), 'status':1}
    else:
        data = {'status':0}
    return data

def get_info(cliente_mqtt):
    try:
            
        if cliente_mqtt.connected == False: #deberia poner un try/except para las conexiones mqtt
            cliente_mqtt = Mqtt(broker=BROKER, topic='#')
        cliente_mqtt.publish_message(topico=TOPIC, msg='info')
        time.sleep(1)
        informacion = cliente_mqtt.informacion


    except Exception as e:
        informacion = False #OJO

    finally:
        return informacion




@csrf_exempt 
def connect_view(request):
    if request.method=='GET':
        
        networks = False
        while networks == False:
            try:
                networks = scan()
            except Exception as e:
                networks = False
                time.sleep(5)

        contexto = {'networks':networks}

        return render(request,'networks.html', contexto)
    else:
        wifi = request.POST['wifi']
        status = connect_wifi(ssid=wifi, password=str(settings.WIFI_PASSWORD))

        return redirect('screen:menu_view')





def menu_view(request):
    global cliente_mqtt

    cliente_mqtt = Mqtt(broker=BROKER, topic='#') #Cambiar por direccion ip por host con el scanner
    return render(request,'menu.html', {})



@csrf_exempt 
def map_view(request):
    data = get_coord(cliente_mqtt)

    if request.method=='GET':
        return render(request, 'map.html', data)

    elif request.method=='POST': #AJAX
        return HttpResponse(json.dumps(data,cls=DjangoJSONEncoder))




def info_view(request):
    try:
        info = get_info(cliente_mqtt)
    except NameError :
        cliente_mqtt = Mqtt(broker=BROKER, topic='#')
        info = get_info(cliente_mqtt)



    contexto = {'contexto':info}
    return render(request,'informacion.html', contexto)

templates/informacion.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Mapa</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
        <link rel="stylesheet" href="{% static 'css/map.css'%}">
    </head>


    <body>
        
        <div>
            <h1>INFORMACION</h1>
            
            <h3>Sinapsis ID: {{contexto.sinapsis_id}}</h3>
            <h3>Coordenadas: {{contexto.coordenadas}}</h3>
            <h3>Internet: {{contexto.internet}}</h3>
            <h3>Consumo de Procesamiento {{contexto.cpu}}%</h3>


        </div>        

    </body>
</html>

templates/map.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Mapa</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'leaflet/leaflet.css'%}">
        <link rel="stylesheet" href="{% static 'css/map.css'%}">
    </head>


    <body>
        
        <div class="mapstyle" id="mapid" style="width: 100vw; height: 100vh;"></div>
        
        
        <script type="text/javascript">
            var status = '{{status}}'
            
            if (status!=0){
                var lat = '{{lat}}';
                var lng = '{{lng}}';
                var zoom = 18
                
            }else{
                var lat = 10.4764;
                var lng = -66.8421;
                var zoom = 11
                // alert('GPS No disponible')
            }
            
        </script>
      
      
      <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

      <script src="{% static 'leaflet/leaflet.js' %}"></script>

      <script src="{% static 'js/map.js' %}"></script>
        

    </body>
</html>

templates/menu.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/menu.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" media="screen">

    <title>Document</title>
</head>
<body>

        <div class="toggle" id="toggle" onclick="menu-expand()">
                <i class="fa fa-plus" id="plus"></i>
                  </div>
                <div class="menu" id="menu">
                  <a href="{% url 'screen:map_view' %}">
                    <i class="fa fa-street-view"></i>
                  </a>
                   <a href="{% url 'screen:info_view' %}">
                    <i class="fa fa-info-circle"></i>
                  </a>
                  <a href="#">
                    <i class="fa fa-video-camera"></i>
                  </a>
                  <a href="#">
                    <i class="fa fa-envelope"></i>
                  </a>
                  <a href="#">
                    <i class="fa fa-camera"></i>
                  </a>
                  <a href="#">
                    <i class="fa fa-bell"></i>
                  </a>
                </div>
                
<script src="{% static 'js/menu.js' %}"></script>
  
</body>
</html>

templates/networks.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/networks.css' %}" rel="stylesheet" media="screen">

    <title>Document</title>
</head>
<body>
        <form method="post" name="form" enctype="multipart/form-data" action="{% url 'screen:connect_view' %}">
            <div class="btn-group">
                {% for n in networks%}
                    <input type="submit" class="button" name="wifi" value="{{n}}">
                {% endfor %}
            </div>
        </form>
                
  
</body>
</html>